apiVersion: v1
kind: Service
metadata:
  name: user-mysql-service-lb
  labels:
    app: user-mysql-service-lb
spec:
  ports:
  - port: 3307
    targetPort: 3306
    protocol: TCP
    name: mysql
  selector:
    app: user-mysql
  type: LoadBalancer