apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-mysql-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data2"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: user-mysql
spec:
  selector:
    matchLabels:
      app: user-mysql
  serviceName: "user-mysql-stateful"
  replicas: 1
  # strategy:
  #   type: Recreate
  template:
    metadata:
      labels:
        app: user-mysql
    spec:
      containers:
        - image: mysql:8.0
          name: user-mysql-image-name
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: keycloak_db
          ports:
            - containerPort: 3306
              name: user-mysql-port
          volumeMounts:
            - name: user-mysql-persistent-storage
              mountPath: /var/lib/mysql
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: user-mysql-persistent-storage
          persistentVolumeClaim:
            claimName: user-mysql-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: user-db
  labels:
    app: user-db
spec:
  ports:
    - protocol: TCP
      port: 3307
      targetPort: 3306
  selector:
    app: user-mysql
  clusterIP: None