apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-app
  labels:
    app: user-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app : user-service-app
  template:
    metadata:
      labels:
        app: user-service-app
    spec:
      containers:
      - name: user-service-app
        image: ashan97/pot-v2-user-ms:1.00
        imagePullPolicy: Always
        ports:
          - containerPort: 8081
        env:
          - name: MYSQL_HOST
            value: user-db
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
---

kind: Service
apiVersion: v1
metadata:
  name:  user-service-svc
spec:
  selector:
    app:  user-service-app
  type: ClusterIP
  ports:
  - port:  8081
    targetPort:  8081