apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-mysql-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data2"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak-mysql
spec:
  selector:
    matchLabels:
      app: keycloak-mysql
  serviceName: "keycloak-mysql"
  replicas: 1
  # strategy:
  #   type: Recreate
  template:
    metadata:
      labels:
        app: keycloak-mysql
    spec:
      containers:
        - image: mysql:5.7
          name: keycloak-mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: keycloak_db
          ports:
            - containerPort: 3306
              name: keycloak-mysql
          volumeMounts:
            - name: keycloak-mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: keycloak-mysql-persistent-storage
          persistentVolumeClaim:
            claimName: keycloak-mysql-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-mysql
  labels:
    app: keycloak-mysql
spec:
  ports:
  - port: 3306
    protocol: TCP
    name: mysql
  selector:
    app: keycloak-mysql
  type: LoadBalancer


# apiVersion: v1
# kind: Service
# metadata:
#   name: keycloak-mysql
# spec:
#   ports:
#     - protocol: TCP
#       port: 3307
#       targetPort: 3306

#   selector:
#     app: keycloak-mysql
#   clusterIP: None